### ISSUE TITLE
fast-boot is not compatible with babel-core@6

### ISSUE THREAD

**Issue by dantman** [wix/fast-boot#1]
In `babel-core/lib/helpers/resolve.js` a call to `module._resolveFilename` is made. It's passed the module name for something like the `babel-preset-es2015` and a relativeMod module made via:

``` js
relativeMod = new module();
relativeMod.paths = module._nodeModulePaths(relative);
```

This works fine and returns the path to index.js in the module normally. But when `fast-boot` is present it instead throws the error `[TypeError: Path must be a string. Received undefined]`. babel-core then swallows and silences that error. Then decides the module doesn't exist and throws `Error: Couldn't find preset "es2015" relative to directory "..."`.

**Comment by dantman** [comment]
This seems to be because `parent.id` is `undefined` in this situation.

**Comment by Gvozd** [comment]
I also encountered with this problem
I tried to use fast-boot with babel-register

```
node -r ../fast-boot.js -r babel-register -r babel-regenerator-runtime ./index.js
```

And get this Error

```
c:\Projects\github-worked\json-search-engine\node_modules\fast-boot\index.js:42
  var key = (toCanonicalPath(parent.id) + ":" + request );
                                   ^
TypeError: Cannot read property 'id' of null
    at Function.resolveFilenameOptimized [as _resolveFilename] (c:\Projects\github-worked\json-search-engine\node_modules\fast-boot\index.js:42:36)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by Gvozd** [comment]
I run tests for this module.
Not all tests passed

And it's look as it is no longer need for current node/npm

```
        - first run  [1.0.0]: 0.126303077 Sec, statSync: 0, readFileSync: 57, existsSyncCount: 7
        - second run  [1.0.0]: 0.091725919 Sec, statSync: 0, readFileSync: 57, existsSyncCount: 100

        - first run  [1.0.0]: 0.135034644 Sec, statSync: 0, readFileSync: 58, existsSyncCount: 7
        - second run  [1.0.0]: 0.089608837 Sec, statSync: 0, readFileSync: 58, existsSyncCount: 100

        - first run  [1.0.0]: 0.119314002 Sec, statSync: 0, readFileSync: 57, existsSyncCount: 7
        - second run  [1.0.0]: 0.105518559 Sec, statSync: 0, readFileSync: 57, existsSyncCount: 100
        - second run  [1.0.0]: 0.342282265 Sec, statSync: 0, readFileSync: 170, existsSyncCount: 112
```

Has no statSync for optimizing
readFileSync with plugin not less without plugin
existsSyncCount more with plugin
loadingTime bigger at third run

I think need new way for optimizing babel start time

**Comment by Gvozd** [comment]
@dantman

I some profile load time (uses last node & **npm**)
Babel load time can not be significantly optimized
Most of load time  - is real execuiton code, not FS-operations (

So, this module (and any similar, like `cache-require-source/paths` or `zipread` hooks) can not solve the problem of the long download for Babel
